<a href="https://colab.research.google.com/github/myname-baskaran/AI-JOURNEY/blob/main/Day13_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Day 13 - Review: Pandas So Far

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({"Ticker": ["DBS", "OCBC", "UOB", "SIA", "Grab", "SeaLtd"],
    "Price":  [35.20, 14.80, 31.50, 6.40, 4.10, 78.30],
    "Sector": ["Banking", "Banking", "Banking", "Airline", "Tech", "Tech"]})

In [4]:
df.head(3)

  Ticker  Price   Sector
0    DBS   35.2  Banking
1   OCBC   14.8  Banking
2    UOB   31.5  Banking

In [9]:
shape = df.shape
print(shape)

(6, 3)

In [13]:
df[df['Price'] > 30]

   Ticker  Price   Sector
0     DBS   35.2  Banking
2     UOB   31.5  Banking
5  SeaLtd   78.3     Tech

In [21]:
print(df['Price'].mean())

28.383333333333336

In [22]:
print(df['Sector'].value_counts())

Sector
Banking    3
Tech       2
Airline    1
Name: count, dtype: int64

In [24]:
df['Price_USD'] = df['Price'].map(lambda p: p * 0.74)
print(df['Price_USD'])

0    26.048
1    10.952
2    23.310
3     4.736
4     3.034
5    57.942
Name: Price_USD, dtype: float64